---
title: "Le traitement des occupations universitaires par le Temps"
author: "Vestin Hategekimana & Nicolas Oclei"
format: 
  html:
    page-layout: full
editor: visual
---

```{r}
#| warning: false
#| message: false
#| echo: false
# Libraries ----
library(tidyverse, DT)
source("Script/utilities.R")

# Options ----
span <- function(x, color="blue"){
  str_c('<span style="color:', color, '">', x, "</span>")
}

remove_long <- function(text){
  if_else(
    str_length(text) > 120 | str_length(text) < 3,
    "",
    text
  )
}

# data ----
df2 <- read_rds("MyData/df2.rds")

max_date <- max(df2$date)
min_date <- min(df2$date)

type_position <-
  readxl::read_xlsx("Data/Le temps occupation universitaire type et position.xlsx") %>% 
  mutate_all(str_to_lower) %>% 
  rename_with(.fn = str_to_lower) %>% 
  select(-article)
```


## Tableau des articles du `r stamp("1 Mai 2024")(min_date)` au `r stamp("1 Mai 2024")(max_date)`

```{r}
#| warning: false
#| message: false
#| echo: false

to_remove <- 0 - c(2, 7, 8, 12, 16, 18, 31, 36:38, 40, 43, 47:48, 53:55, 57:58, 61:69, 72:73, 75:80, 82:84, 86, 88, 91:95, 99:104)

# Tableau
tableau <-
  df2 %>% 
  arrange(titre, desc(type), desc(position), desc(ton)) %>% 
  group_by(titre) %>%
  slice_head(n=1) %>%
  ungroup() %>%
  select(titre, date, url=lien, auteur, lieu, acteurs, critique) %>%
  mutate(
    url = str_c(
      '<a href="',
      url,
      '">lien</a>'
    )
    ) %>% 
  distinct() %>% 
  arrange(date) %>% 
  slice(
    to_remove
  ) %>% 
  bind_cols(type_position) %>% 
  mutate(
    position = case_match(
      position,
      "pour" ~ span("pour", "green"),
      "contre" ~ span("contre", "red"),
      .default = span(position, "blue")
    ),
    across(type:position, remove_long)
  )

tableau %>% 
  DT::datatable(escape = FALSE)
```

------------------------------------------------------------------------

## Articles de Laure Lugon Zugravu

```{r}
#| warning: false
#| message: false
#| echo: false

tableau %>% 
  filter(str_detect(auteur, "Zugravu")) %>% 
  DT::datatable(escape = FALSE)
```
